version: '3.8'
services:
  mongo-db:
    image: mongo:7.0
    restart: always #cuando se levante el docker se levante tambien lo levante la imagen.
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27018:27017